### ISSUE TITLE
Redirect to success page after checkout not working

### ISSUE THREAD

**Issue by matin73** [heidelpay/magento2#82] opened 2018-09-28 06:38 UTC
Hello,

we have Magento 2.2.6 installation. After sucess payment (sandbox modus) your modul is not redirecting correct to sucess page. It always redirects to cart page. Message shown in cart is "no items in cart". And also minicart is not emptied.
Martin

**Comment by matin73** [comment] 2018-09-28 15:38
I have checked logs, but there are no entries at all.

**Comment by matin73** [comment] 2018-09-28 16:12
I also have this problem https://github.com/heidelpay/magento2/issues/74

**Comment by matin73** [comment] 2018-09-29 17:10
It seems that in file vendor/magento/module-checkout/Controller/Onepage/Success.php session is somehow lost and code returns 302 redirect to cart:
 if (!$this->_objectManager->get(\Magento\Checkout\Model\Session\SuccessValidator::class)->isValid()) {
            return $this->resultRedirectFactory->create()->setPath('checkout/cart');
        }

**Comment by matin73** [comment] 2018-09-29 17:33
Seems problem is already known https://github.com/heidelpay/magento2/issues/70

**Comment by Ryouzanpaku** [comment] 2018-10-01 07:01
In that case i close this issue.
#74 is solved in version 18.8.9.

**Comment by matin73** [comment] 2018-10-01 07:07
Where can I download version 18.8.9.???

**Comment by matin73** [comment] 2018-10-01 07:09
Please also update your installation manual https://github.com/heidelpay/magento2 - composer require "heidelpay/magento2:17.10.12" seem not correct !!

**Comment by Ryouzanpaku** [comment] 2018-10-01 07:17
You can find the releases here: https://github.com/heidelpay/magento2/releases
Thank you for the hint, I will check the installation manual again.

**Comment by matin73** [comment] 2018-10-01 08:33
I run 
composer require "heidelpay/magento2:18.9.20"
and
composer update heidelpay/magento2
and I got message 
Nothing to install or update

So, I have latest version - but same error - I get redirected to cart

**Comment by matin73** [comment] 2018-10-01 08:55
I know completly removed extension by
composer remove "heidelpay/magento2"

and then reinstalled 
composer require "heidelpay/magento2:18.9.20"

same issue! I get redirected to cart

**Comment by Ryouzanpaku** [comment] 2018-10-02 13:09
Thats the issue #70. So far we have not found a solution to handle that in our plugin. You can check that for further information.
This error occurs in combination with full page cache and synchronous mail delivery.

**Comment by matin73** [comment] 2018-10-02 13:42
???? every other payment-provider has solution for it? this is realy anoying ...

**Comment by matin73** [comment] 2018-10-02 13:50
Why is ticket https://github.com/heidelpay/magento2/issues/70 closed? Bug still open!

**Comment by benbrownsen** [comment] 2018-11-12 12:10
Issue is still there. used version: 18.10.1
Getting a blank site with the url showing. Logs:

[2018-11-12 11:41:57] main.WARNING: Heidelpay - Response: Request is not POST.

**Comment by sixer1182** [comment] 2018-11-12 12:46
Hi @benbrownsen,
this is a different issue.
The most probable cause is that the response url is not accessable from the web.
Please create an issue sending an email to development@heidelpay.com with the shortId of your transaction.

Hi @matin73,
In order to analyze please create a ticket by sending an email to development@heidelpay.com as well.

Yours Simon

**Comment by matin73** [comment] 2018-11-12 13:16
@sixer1182 I was already in contact with support@heidelpay.de - but they are even not able to setup magento at all they say (!?!?!?). I stopped using heidelpay at all, because this is unbeliveable!!!

**Comment by matin73** [comment] 2018-11-12 13:19
this is what heidlpay support told me - original text from email!!
"Tests mit FP-Caching sind uns technisch aktuell nicht möglich. Wir versuchen seit 6 Wochen einen Test-Server aufzusetzen zu lassen, der innerhalb unserer Sicherheitsrichtlinien auch ein FPC aktivieren lässt ..."

Sorry, but FP-Caching is Magento default. This is realy anoying getting such emails!

**Comment by sixer1182** [comment] 2018-11-13 15:33
I understand your frustration.
We are having trouble reproducing the error which is why we tried to emulate the environments in which we knew the error has been spotted. I would be grateful if you could provide me with the information of your system and magento config (different from default): php version, webserver, etc.

**Comment by matin73** [comment] 2018-11-13 17:17
I sent ftp, ssh and admin login to support. More I can not do ...

**Comment by sixer1182** [comment] 2018-11-13 18:58
In this case please send me the ticket-id.

**Comment by matin73** [comment] 2018-11-14 06:49
FCL-VYSQQ-188

**Comment by sixer1182** [comment] 2018-11-29 13:05
As of today we will disable issue tracking on GitHub.
This is due to most of the issues actually being support issues due to usage problems.
Please send your requests to support@heidelpay.com to receive a Ticket-Number.
We are sorry for any inconvenience this will cause you.
Thanks for understanding,
your HeidelpayDev team.

**Closed by sixer1182** 2018-11-29 13:05 UTC
